import type { Metadata } from "next";
import "./globals.css";
import { jakarta_regular } from "@/fonts/fonts";
import { GlobalContextProvider } from "./context/global.context";

export const metadata: Metadata = {
  title: "Main Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
       <GlobalContextProvider>
        <body className={jakarta_regular.className}>
          {children}
        </body>
      </GlobalContextProvider>
    </html>
  );
}
